-- Tabela para auditar ações nos agendamentos
create table public.appointment_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  action_type text not null, -- 'CREATE', 'UPDATE', 'DELETE', 'RESCHEDULE', 'COMPLETE'
  performed_by uuid references auth.users(id),
  appointment_id uuid,
  details text,
  old_data jsonb, -- Como era antes
  new_data jsonb  -- Como ficou depois
);

-- Habilitar RLS
alter table public.appointment_logs enable row level security;

-- Políticas de Segurança
-- Admins podem ver tudo e inserir
create policy "Admins can view all logs"
  on public.appointment_logs for select
  using (
    (select is_admin from public.profiles where id = auth.uid()) = true
  );

create policy "Admins can insert logs"
  on public.appointment_logs for insert
  with check (
    (select is_admin from public.profiles where id = auth.uid()) = true
  );
  
-- (Opcional) Usuários normais podem inserir logs se eles mesmos fizerem ações (ex: cancelar pelo perfil)
create policy "Users can insert own logs"
  on public.appointment_logs for insert
  with check (
    auth.uid() = performed_by
  );