create table if not exists public.email_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  to_email text not null,
  subject text not null,
  type text, -- e.g. 'confirmation', 'welcome'
  status text default 'sent',
  error_message text,
  metadata jsonb
);

-- Enable RLS
alter table public.email_logs enable row level security;

-- Policies
create policy "Admins can view all email logs"
  on public.email_logs for select
  using (
    (select is_admin from public.profiles where id = auth.uid()) = true
  );

create policy "Service role can insert email logs"
  on public.email_logs for insert
  with check (true);